CREATE DATABASE CAR_RENT;

CREATE TABLE CAR(
    CAR_ID VARCHAR(10) PRIMARY KEY,
	BRAND VARCHAR(60) NOT NULL,
	MODEL VARCHAR(60) NOT NULL
)

CREATE TABLE CLIENT(
    CLIENT_ID INT PRIMARY KEY,
    FNAME VARCHAR(50) NOT NULL,
	LNAME VARCHAR(50) NOT NULL
)



CREATE TABLE RENT(
   CLIENT_ID INT NOT NULL FOREIGN KEY REFERENCES CLIENT,
   CAR_ID VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES CAR,
   RENT_DATE DATETIME NOT NULL,
   PRICE FLOAT NOT NULL CHECK (PRICE > 0)
   PRIMARY KEY(CLIENT_ID, CAR_ID)
)



ALTER TABLE CAR
ADD COLOR VARCHAR(20)


INSERT INTO CAR(CAR_ID, BRAND, MODEL, COLOR)
VALUES('PB 2342 AP', 'Audi', 'V1', 'White')
INSERT INTO CAR(CAR_ID, BRAND, MODEL, COLOR)
VALUES('SM 5672 AP', 'BMW', 'A1', 'Black')
INSERT INTO CAR(CAR_ID, BRAND, MODEL, COLOR)
VALUES('BR 8632 AP', 'Mitsubishi', 'C1', 'White')

INSERT INTO CLIENT(CLIENT_ID, FNAME, LNAME)
VALUES(1, 'Alex', 'Dimitrov')
INSERT INTO CLIENT(CLIENT_ID, FNAME, LNAME)
VALUES(2, 'Maria', 'Ivanova')
INSERT INTO CLIENT(CLIENT_ID, FNAME, LNAME)
VALUES(3, 'Peter', 'Ivanov')

INSERT INTO RENT(RENT_ID, CLIENT_ID, CAR_ID, RENT_DATE, PRICE)
VALUES(1, 'PB 2342 AP', convert(datetime, '12-12-1999', 105), 192.12)
INSERT INTO RENT(RENT_ID, CLIENT_ID, CAR_ID, RENT_DATE, PRICE)
VALUES(2, 'PB 5672 AP', convert(datetime, '12-02-2009', 105), 100)
INSERT INTO RENT(RENT_ID, CLIENT_ID, CAR_ID, RENT_DATE, PRICE)
VALUES(3, 'PB 2342 AP', convert(datetime, '02-02-2012', 105), 107)
INSERT INTO RENT(RENT_ID, CLIENT_ID, CAR_ID, RENT_DATE, PRICE)
VALUES(1, 'BR 8632 AP', '2002-08-20', 107)
INSERT INTO RENT(RENT_ID, CLIENT_ID, CAR_ID, RENT_DATE, PRICE)
VALUES(1, 'BR 8632 AP', GETDATE(), 107)


UPDATE CAR
SET COLOR = 'Grey'
WHERE BRAND = 'Mitsubishi'


SELECT COUNT(*) AS TOTAL_COUNT
FROM RENT
WHERE YEAR(RENT_DATE) = 2002



SELECT (C.FNAME + ' ' + C.LNAME) AS NAME, SUM(R.PRICE)
FROM CLIENT AS C
LEFT JOIN RENT AS R ON R.CLIENT_ID = C.CLIENT_ID
GROUP BY C.FNAME + ' ' + C.LNAME


CREATE VIEW CAR_INFO
AS
SELECT CAR.BRAND, CAR.MODEL, COUNT(CAR.CAR_ID) AS TOTAL
FROM CAR
JOIN RENT ON RENT.CAR_ID = CAR.CAR_ID
GROUP BY BRAND, MODEL
HAVING COUNT(CAR.CAR_ID) > 3


SELECT * FROM CAR_INFO

