CREATE DATABASE SUPPLIES;

CREATE TABLE SUPPLIERS (
     SID CHAR(10) PRIMARY KEY,
	 NAME VARCHAR(20) NOT NULL
)

CREATE TABLE PARTS (
     PART_ID INT PRIMARY KEY,
	 NAME VARCHAR(20) NOT NULL
)

CREATE TABLE SUPPLIERS_PARTS(
     SID CHAR(10) FOREIGN KEY REFERENCES SUPPLIERS,
	 PART_ID INT FOREIGN KEY REFERENCES PARTS,
	 QUANTITY INT,
	 PRIMARY KEY(SID, PART_ID)
)


ALTER TABLE SUPPLIERS_PARTS
ADD PRICE INT CHECK(PRICE >= 1 OR PRICE <= 33) NOT NULL



INSERT INTO SUPPLIERS(SID, NAME)
VALUES ('A213', 'SUPPLIERS NAME')

INSERT INTO PARTS(PART_ID, NAME)
VALUES (1, 'PART NAME')

INSERT INTO SUPPLIERS_PARTS(SID, PART_ID, QUANTITY, PRICE)
VALUES ('A213', 1, 3, 23)


DELETE FROM SUPPLIERS 
WHERE NAME = 'Trade'


SELECT S.NAME, SP.PART_ID
FROM SUPPLIERS AS S
JOIN SUPPLIERS_PARTS AS SP ON SP.SID = S.SID
WHERE S.NAME = 'S'
ORDER BY NAME DESC



SELECT P.NAME, SUM(SP.PRICE*SP.QUANTITY) AS TOTAL
FROM PARTS AS P
JOIN SUPPLIERS_PARTS AS SP ON P.PART_ID = SP.PART_ID
GROUP BY P.NAME
HAVING SUM(SP.PRICE*SP.QUANTITY) > 17
ORDER BY SUM(SP.PRICE*SP.QUANTITY) ASC




CREATE VIEW SUPPLIES_VIEW
AS
SELECT S.SID, SUM(SP.QUANTITY) AS TOTAL
FROM SUPPLIERS AS S
LEFT JOIN SUPPLIERS_PARTS AS SP ON SP.SID = S.SID
GROUP BY S.SID

SELECT * FROM SUPPLIES_VIEW
