SELECT *
FROM REGIONS 

SELECT *
FROM COUNTRIES 

DELETE FROM REGIONS
WHERE REGION_ID = 1

SELECT *
FROM EMPLOYEES

--WE CAN NOT DELETE THIS RECORD
DELETE FROM EMPLOYEES
WHERE EMPLOYEE_ID = 100

DELETE FROM EMPLOYEES
WHERE EMPLOYEE_ID = 206


SELECT *
FROM EMPLOYEES 
WHERE DEPARTMENT_ID = 30

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 1000

SELECT *
FROM DEPARTMENTS
WHERE DEPARTMENT_ID = 1000

DELETE FROM DEPARTMENTS
WHERE DEPARTMENT_ID = 30

INSERT INTO DEPARTMENTS(DEPARTMENT_ID, NAME, COUNTRY_ID, CITY)
VALUES(1000, 'DEFAULT', 'US', 'NY')

SELECT *
FROM ORDERS

SELECT *
FROM ORDER_ITEMS
WHERE ORDER_ID = 2354

DELETE FROM ORDERS
WHERE ORDER_ID = 2354