CREATE DATABASE INSTAGRAM_PROJECT;

CREATE TABLE USERPROFILE (
	UserId INT PRIMARY KEY IDENTITY (1, 1),
	Username VARCHAR(255) UNIQUE,
	Password VARCHAR(100) NOT NULL,
	Name VARCHAR(50),
	Email VARCHAR(100) UNIQUE,
	PhoneNumber VARCHAR(20),
	Birthday DATE,
	Pronouns VARCHAR(10),
	Bio VARCHAR(255),
	Gender VARCHAR(10),
	ProfilePicture VARBINARY(MAX)
);

CREATE TABLE FOLLOWINGLIST(
	FollowingUserId INT NOT NULL,
	FollowerUserId INT NOT NULL,
	FOREIGN KEY (FollowingUserId) REFERENCES USERPROFILE(UserId), 
    FOREIGN KEY (FollowerUserId) REFERENCES USERPROFILE(UserId),
    UNIQUE (FollowingUserId, FollowerUserId)
);

CREATE TABLE CONTENT(
	ContentId INT PRIMARY KEY IDENTITY (1, 1),
	PosterId INT NOT NULL,
	Date DATETIME DEFAULT GETDATE(),
	Location VARCHAR(255),
	Caption VARCHAR(255),
	Likes INT DEFAULT 0,
	Music VARCHAR(255),
	FOREIGN KEY (PosterId) REFERENCES USERPROFILE(UserId), 
);

CREATE TABLE COMMENT(
	CommentId INT PRIMARY KEY IDENTITY (1, 1),
	Comment VARCHAR(255) NOT NULL,
	Likes INT DEFAULT 0,
	ContentId INT NOT NULL,
	Commenter INT NOT NULL,
	FOREIGN KEY (Commenter) REFERENCES USERPROFILE(UserId), 
	FOREIGN KEY (ContentId) REFERENCES CONTENT(ContentId), 
);

CREATE TABLE TAG(
	TagId INT PRIMARY KEY IDENTITY (1, 1),
	ContentId INT NOT NULL,
	TaggedUserId INT NOT NULL,
	FOREIGN KEY (TaggedUserId) REFERENCES USERPROFILE(UserId), 
	FOREIGN KEY (ContentId) REFERENCES CONTENT(ContentId), 
);

CREATE TABLE REEL(
	ReelId INT PRIMARY KEY IDENTITY (1, 1),
	Video VARBINARY(MAX) NOT NULL,
	Fundraiser VARCHAR(255),
	SharesCount INT DEFAULT 0,
	ContentId INT NOT NULL,
	FOREIGN KEY (ContentId) REFERENCES CONTENT(ContentId), 
);

CREATE TABLE POST(
	PostId INT PRIMARY KEY IDENTITY (1, 1),
	PartnershipLabelId INT,
	ContentId INT NOT NULL,
	FOREIGN KEY (PartnershipLabelId) REFERENCES USERPROFILE(UserId), 
	FOREIGN KEY (ContentId) REFERENCES CONTENT(ContentId), 
);

CREATE TABLE PHOTO(
	PhotoId INT PRIMARY KEY IDENTITY (1, 1),
	UserId INT NOT NULL,
	PostId INT NOT NULL,
	Photo VARBINARY(MAX) NOT NULL,
	FOREIGN KEY (UserId) REFERENCES USERPROFILE(UserId), 
	FOREIGN KEY (PostId) REFERENCES POST(PostId), 
);

CREATE TABLE STORY(
	StoryId INT PRIMARY KEY IDENTITY(1,1),
	Photo VARBINARY(MAX) NOT NULL,
	Date DATETIME DEFAULT GETDATE(),
	Location VARCHAR(255),
	Mention VARCHAR(255),
	Music VARCHAR(255),
	ViewsCount INT DEFAULT 0,
	Likes INT DEFAULT 0,
	UserID INT NOT NULL,
	FOREIGN KEY (UserId) REFERENCES USERPROFILE(UserId), 
);

CREATE TABLE HIGHLIGHT(
	HighlightId INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(255) NOT NULL,
	CoverPhoto VARBINARY(MAX) NOT NULL,
);

CREATE TABLE STORY_HIGHLIGHT(
	HighlightId INT NOT NULL,
	StoryId INT NOT NULL,
	FOREIGN KEY (HighlightId) REFERENCES HIGHLIGHT(HighlightId), 
    FOREIGN KEY (StoryId) REFERENCES STORY(StoryId),
    UNIQUE (HighlightId, StoryId)
);
