SELECT AVG(Likes) AS AVG_LIKES
FROM CONTENT;


SELECT MAX(ViewsCount) AS AVG_LIKES
FROM STORY;


SELECT MIN(SharesCount) AS AVG_LIKES
FROM REEL;


SELECT COUNT(UserId) as UserCount, MONTH(Birthday) as BirthdayMonth 
FROM USERPROFILE
GROUP BY MONTH(Birthday)
ORDER BY UserCount DESC;
