CREATE TABLE PRODUCT(
   ID INT PRIMARY KEY,
   NAME VARCHAR(100) NOT NULL,
   QUANTITY INT NOT NULL,
)

CREATE TABLE COMPONENT(
   ID INT PRIMARY KEY,
   NAME VARCHAR(100) NOT NULL,
   DESCRIPTION VARCHAR(500)
)

CREATE TABLE SUPPLIER(
   ID INT PRIMARY KEY,
   NAME VARCHAR(100) NOT NULL,
)

CREATE TABLE COMPONENT_PRODUCT(
   COMPONENT_ID INT FOREIGN KEY REFERENCES COMPONENT,
   PRODUCT_ID INT FOREIGN KEY REFERENCES PRODUCT,
   CONSTRAINT PK_COMPONENT_PRODUCT PRIMARY KEY(COMPONENT_ID, PRODUCT_ID)
)

CREATE TABLE COMPONENT_SUPPLIER(
   COMPONENT_ID INT FOREIGN KEY REFERENCES COMPONENT,
   SUPPLIER_ID INT FOREIGN KEY REFERENCES SUPPLIER,
   CONSTRAINT PK_COMPONENT_PRODUCT PRIMARY KEY(COMPONENT_ID, SUPPLIER_ID)
)
