CREATE DATABASE CD_CATALOGUE

CREATE TABLE CD(
   ID INT PRIMARY KEY,
   TITLE VARCHAR(100) NOT NULL,
   PRICE FLOAT NOT NULL,
   GENRE VARCHAR(50) NOT NULL,
   ARTIST_ID INT FOREIGN KEY REFERENCES ARTIST,
)

CREATE TABLE ARTIST(
   ID INT PRIMARY KEY,
   NAME VARCHAR(100) NOT NULL,
)

CREATE TABLE TRACK(
   ID INT PRIMARY KEY,
   TITLE VARCHAR(100) NOT NULL,
   RUNNING_TIME INT NOT NULL,
)

CREATE TABLE TRACK_ARTIST(
   TRACK_ID INT FOREIGN KEY REFERENCES TRACK,
   ARTIST_ID INT FOREIGN KEY REFERENCES ARTIST,
   CONSTRAINT PK_TRACK_ARTIST PRIMARY KEY(TRACK_ID, ARTIST_ID)
)

CREATE TABLE TRACK_CD(
   TRACK_ID INT FOREIGN KEY REFERENCES TRACK,
   CD_ID INT FOREIGN KEY REFERENCES CD,
   CONSTRAINT PK_TRACK_CD PRIMARY KEY(TRACK_ID, CD_ID)
)

