CREATE TABLE GENRES(
   ID INT PRIMARY KEY,
   NAME VARCHAR(100) UNIQUE NOT NULL,
   DESCRIPTION VARCHAR(500),
)

CREATE TABLE AUTHORS(
   ID INT PRIMARY KEY,
   NAME VARCHAR(100) NOT NULL,
   BIOGRAPHY VARCHAR(1000) NOT NULL,
)

CREATE TABLE BOOKS(
   ID INT PRIMARY KEY,
   TITLE VARCHAR(100) NOT NULL,
   DESCRIPTION VARCHAR(1000),
   ISBN VARCHAR(50) NOT NULL,
   GENRE VARCHAR(100) NOT NULL,
)

CREATE TABLE BOOKS_AUTHORS(
   BOOKS_ID INT FOREIGN KEY REFERENCES BOOKS,
   AUTHORS_ID INT FOREIGN KEY REFERENCES AUTHORS,
   IS_MAIN_AUTHOR BIT,
   CONSTRAINT PK_BOOKS_AUTHORS PRIMARY KEY(BOOKS_ID, AUTHORS_ID)
)


