CREATE DATABASE University


CREATE TABLE STUDENT(
    ID INT PRIMARY KEY,
	FNAME CHAR(50) NOT NULL,
	LNAME CHAR(50) NOT NULL,
	FACULTY_NUMBER CHAR(100) NOT NULL,
	PHOTO VARBINARY,
	DATE DATETIME NOT NULL,
)

CREATE TABLE TOWN(
    ID INT PRIMARY KEY,
	NAME CHAR(200) NOT NULL,
)

CREATE TABLE COURSE(
    ID INT PRIMARY KEY,
	TOWN_ID INT FOREIGN KEY REFERENCES TOWN,
)

CREATE TABLE STUDENT_COURSE(
    STUDENT_ID INT NOT NULL,
	COURSE_ID INT NOT NULL,
	CONSTRAINT FK_STUDENT_COURSE PRIMARY KEY(STUDENT_ID, COURSE_ID)
)

